# fly.toml app configuration file generated for hng3-anagrammer on 2025-11-03T17:44:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hng3-anagrammer'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
